### ISSUE TITLE
[APPLICATION ISSUE] APPLICATION CAN ONLY HANDLE A SINGLE ACCOUNT

### ISSUE THREAD

**Issue by dhirentheindian** [SOFENGG-T1AY1617/S18B-Team-Kyle#10]
Description
- As of now, the application can only accept one account (username: test and password: test). The application should accept multiple accounts because there are different checkers for each building in De La Salle University Manila. But, due to this constraint there are some test cases which requires multiple accounts cannot be tested. 

Build/Platform
- Build 3
- Android 6.0.1

Steps to reproduce
- None since it is only an issue within our application.

Actual Result
- Application can only handle a single account.

Expected Result
- Application should be able to handle multiple accounts.

**Comment by Kylitaaaaaa** [comment]
THE APPLICATION CAN ONLY ACCEPT TWO ACCOUNTS. (test, test) and (test2, test). THE DEVELOPMENT TEAM NO LONGER CREATED MORE ACCOUNTS BECAUSE THEIR FOCUS WAS ON FINISHING THE MOBILE APPLICATION.
