### ISSUE TITLE
DISPLAY ISSUE IN THE CLASSES UNDER THE DONE TAB

### ISSUE THREAD

**Issue by Kylitaaaaaa** [SOFENGG-T1AY1617/S18B-Team-Kyle#12]
Description
 - Sometimes the classes under the done tab does not contain the most recent update. When viewed, it will not show the selected status of the class. For this bug to happen, the user must switch tabs, do edits, and view other classes. The bug happens any time while using the application.

Steps to reproduce:
1. Navigate to the application.
2. Type in valid username and password.
3. Click login button.
4. Check the attendance for an assigned class.
5. Go to the done tab.
6. View the class that has recently been checked.
7. Go back to the current tab.
8. View any assigned class.
9. Keep switching between the current and done tabs.

Build/Platform
- Build 3
- Android 6.0.1

Actual Result
![screenshot_20161213-125938](https://cloud.githubusercontent.com/assets/15272611/21080413/9de55d2e-bfe9-11e6-82b7-28445bec4705.png)
- The selected status is not shown anymore.

Expected Result
![15515794_120300001119718709_593500746_o](https://cloud.githubusercontent.com/assets/22396454/21169285/dbde2526-c1f5-11e6-9e38-342f4cca5005.jpg)
- The most recent selected status of the class is shown.

**Comment by dhirentheindian** [comment]
@Kylitaaaaaa ano na ito

**Comment by Kylitaaaaaa** [comment]
THIS ISSUE HAS BEEN DISREGARDED BECAUSE OUR DEVELOPMENT TEAM CANNOT UNDERSTAND THIS BUG.
