### ISSUE TITLE
[IMPLEMENTATION ISSUE] CODE DESIGN PRINCIPLE ISSUE

### ISSUE THREAD

**Issue by dhirentheindian** [SOFENGG-T1AY1617/S18B-Team-Kyle#2]
Description:
- The mobile application is violating one of the SOLID principles. The collection type "ArrayList" is being used and passed around the different classes. By using this type of collection, it forces all java classes to use only one collection type, which is the "ArrayList". The possible solution for this issue is to use iterators.

Build/Platform
- Build 1
- Android 6.0.0

Steps to reproduce
- None since it is only an issue within the implementation of our application. 

Actual Result
- All Java classes being used are forced to use only one collection type "ArrayList"

Expected Result
- Iterator pattern which enables the application to use more then one collection type.

**Comment by Kylitaaaaaa** [comment]
DUE TO TIME CONSTRAINT AND DIFFICULTY (NEW PROGRAMMING LANGUAGE), IT IS NOT POSSIBLE FOR THE DEVELOPMENT TEAM TO IMPLEMENT SUCH PATTERN.
