### ISSUE TITLE
FRONT END DESIGN ISSUE

### ISSUE THREAD

**Issue by mark2136** [SOFENGG-T1AY1617/S18B-Team-Kyle#3]
Description
- Login button not displaying properly and buttons in the class attendance sheet is also not displaying properly.

Build/Platform
- Build 2
- Android 5.1.1

Steps to reproduce
1. Navigate to the application.
2. Type in valid username and password.
3. Click login button.
4. Select any class that the user wants to evaluate first.

Actual Results
- 
![image](https://cloud.githubusercontent.com/assets/22396454/20396160/3411fe60-ad20-11e6-84ca-ba87663cba0c.png)

- 
![image](https://cloud.githubusercontent.com/assets/22396454/20396136/226d7b12-ad20-11e6-8f1e-67a4ac59158e.png)

Expected Results
- 
![image](https://cloud.githubusercontent.com/assets/22396454/20396245/88360ed2-ad20-11e6-8bb0-df089a5914b6.png)

- 
![image](https://cloud.githubusercontent.com/assets/22396454/20396288/ab69d74e-ad20-11e6-97fb-ba2d27cac3eb.png)

**Comment by mark2136** [comment]
Description
- Login button not displaying properly and buttons in the faculty attendance sheet is also not displaying properly.

Build/Platform
- Build 2
- Android 5.1.1

Steps to reproduce
1. Navigate to the application.
2. Type in valid username and password.
3. Click login button.
4. Select any class that the user wants to evaluate first.

Actual Results
- 
![image](https://cloud.githubusercontent.com/assets/22396454/20396160/3411fe60-ad20-11e6-84ca-ba87663cba0c.png)

- 
![image](https://cloud.githubusercontent.com/assets/22396454/20396136/226d7b12-ad20-11e6-8f1e-67a4ac59158e.png)

Expected Results
- 
![image](https://cloud.githubusercontent.com/assets/22396454/20396245/88360ed2-ad20-11e6-8bb0-df089a5914b6.png)

- 
![image](https://cloud.githubusercontent.com/assets/22396454/20396288/ab69d74e-ad20-11e6-97fb-ba2d27cac3eb.png)

**Comment by Kylitaaaaaa** [comment]
THIS ISSUE HAS BEEN FIXED ALREADY. THIS BUG HAPPENED DUE TO POSSIBLE INCOMPATIBLE SMARTPHONE VERSIONS.
