### ISSUE TITLE
SUBMITTED CLASSES AND THEIR RESPECTIVE STATUS' CAN STILL BE CHANGED

### ISSUE THREAD

**Issue by mark2136** [SOFENGG-T1AY1617/S18B-Team-Kyle#5]
Description
- In our application and acceptance criteria's, we came to an agreement that the user must not be able to change the status of the faculty under the “submitted” tab. Through our testing and consultation with the developers, we found that the application still allows the status of the faculty under the “submitted” tab to be changed by the user. This also goes together with the next bug. This has not yet been fixed for Sprint 2. Will be fixed and reevaluated for the next sprint.

Build/Platform
- Build 2
- Android 5.0.0

Steps to reproduce
1. Navigate to the application.
2. Type in valid username and password.
3. Click login button.
4. Check the attendance for all the assigned classes.
5. Go to the done tab.
6. Click the submit button.
7. Click the Submitted tab.
8. Select any class that has been evaluated.
9. Edit the selected class.
10. Click save.

Actual Result
- Submitted classes and their respective status' can still be changed.

Expected Result
- Submitted classes and their respective status's cannot be changed.

**Comment by Kylitaaaaaa** [comment]
THIS ISSUE HAS BEEN FIXED ALREADY.
