### ISSUE TITLE
FACULTY CARDS NOT DISPLAYING AFTER SUBMITTING FOR A CERTAIN DAY

### ISSUE THREAD

**Issue by mark2136** [SOFENGG-T1AY1617/S18B-Team-Kyle#6]
Description
- After submitting for a certain day, the application will not show any faculty cards for future days. Ex. Submitted for November 17, 2016. When we open the application on November 18, 2016, no faculty cards will be shown. This bug was discovered initially by the developers during their self-testing. So far, this bug has not yet been fixed. This bug is considered as fatal because it will affect the entire user experience due to the application not showing the important information after 1 day.

Build/Platform
- Build 2
- Android 5.0.0

Steps to reproduce
1. Navigate to the application.
2. Type in valid username and password.
3. Click login button.
4. Check the attendance for all the assigned classes.
5. Go to the done tab.
6. Click submit.
7. Logout from the application.
8 Type in valid usernames and password.
9. Click login button.

Actual Result
- Faculty cards not displaying after logging in after a certain day.

Expected Result
- Faculty cards assigned to the user will be shown.

**Comment by Kylitaaaaaa** [comment]
THIS ISSUE HAS BEEN FIXED ALREADY.
