### ISSUE TITLE
SUBMITTED CLASSES MAY APPEAR IN THE WRONG TAB

### ISSUE THREAD

**Issue by mark2136** [SOFENGG-T1AY1617/S18B-Team-Kyle#7]
Description
- This bug occurs because of the back-end progress of our application. There is no database or file where the application saves the values of the “submitted” faculty and their respective status. This has not yet been fixed for Sprint 2. Will be fixed and reevaluated for the next sprint.

Build/Platform
- Build 2
- Android 5.0.0

Steps to reproduce
1. Navigate to the application.
2. Type in valid username and password.
3. Click login button.
4. Check the attendance for all the assigned classes.
5. Go to the done tab.
6. Click submit.
7. Close the application.
8. Navigate to the application again.
9. Type in valid username and password.
10. Click login button.
11. Select done tab.
12. Select current tab.
13. Repeat steps 10 and 11, respectively or vice versa.

Actual Result
- Submitted classes may show randomly in the current or done tabs.

Expected Result
- Submitted classes will only show in the submitted tab.

**Comment by Kylitaaaaaa** [comment]
THIS ISSUE HAS BEEN FIXED ALREADY.
